### ISSUE TITLE
Running the tests, deploying to an internal maven, & updating versions

### ISSUE THREAD

**Issue by jtruelove** [zanox/mod-kafka#8]
How do you run the integration tests/unit tests? I'm running kafka and zookeeper locally like so (version kafka_2.9.2-0.8.1.1)

1) bin/zookeeper-server-start.sh  config/zookeeper.properties
2) bin/kafka-server-start.sh config/server.properties
3) then 'mvn deploy'

but I get an error like so

-------------------------------------------------------
Running com.zanox.vertx.mods.ByteArraySerializerIT
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Starting test: sendMessage
Feb 10, 2015 2:38:12 PM org.vertx.java.core.logging.impl.JULLogDelegate info
INFO: Message sent to kafka topic: default-topic. Payload: VGVzdCBieXRlcyBtZXNzYWdlIQ==
Feb 10, 2015 2:38:12 PM org.vertx.java.core.logging.impl.JULLogDelegate error
SEVERE: Exception in Java verticle
org.junit.ComparisonFailure: expected:<[error]> but was:<[ok]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.zanox.vertx.mods.ByteArraySerializerIT$2.handle(ByteArraySerializerIT.java:71)
	at com.zanox.vertx.mods.ByteArraySerializerIT$2.handle(ByteArraySerializerIT.java:69)
	at org.vertx.java.core.eventbus.impl.DefaultEventBus$11.run(DefaultEventBus.java:951)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

Feb 10, 2015 2:38:12 PM org.vertx.java.core.logging.impl.JULLogDelegate error
SEVERE: Exception in Java verticle
org.junit.ComparisonFailure: expected:<[error]> but was:<[ok]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.zanox.vertx.mods.ByteArraySerializerIT$2.handle(ByteArraySerializerIT.java:71)
	at com.zanox.vertx.mods.ByteArraySerializerIT$2.handle(ByteArraySerializerIT.java:69)
	at org.vertx.java.core.eventbus.impl.DefaultEventBus$11.run(DefaultEventBus.java:951)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

Also, for deploying to your internal maven I'm guessing you just do a 'mvn deploy' is that correct? Any thoughts on updating to the latest version of kafka and vert.x? I was going to test this out when I discovered I couldn't run the 'mvn deploy' command because the unit/integration tests fail. Thanks!

**Comment by jtruelove** [comment]
Any update on this? Do the tests not work anymore?

**Comment by mariamhakobyan-zanox** [comment]
Hi @jtruelove,

Sorry for late response. Usually what we do is run the Zookeeper and Kafka servers locally, and run 'mvn install' and it should run all the tests. Please try that and let me know if that still does not work, it works on my local environment.

Regarding updating to the latest versions, we are planning to do that. If you need it urgently, you are welcome to send a pull request.

Cheers,
Mariam

**Comment by jtruelove** [comment]
Killing my zookeeper and kafka instances 'one' more time seemed like it did the trick. These things can be fickle sometimes I guess. I dropped you a pull request for the updates here:

https://github.com/zanox/mod-kafka/pull/9

**Comment by mariamhakobyan-zanox** [comment]
Great to hear that. I will merge the pull request as soon as I run and verify it locally.

Cheers,
Mariam
